import pathlib, os

BASE = pathlib.Path('backend/app')

def w(rel, content):
    p = BASE / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding='utf-8')
    print(f'  wrote {p} ({len(content)} bytes)')

D = chr(36)
DD = D + D
BT3 = chr(96) * 3
NL = chr(10)
TQ = chr(34) * 3

print('Starting doc engine generation...')

# === doc_planner.py ===
lines = []
lines.append(TQ + 'Doc Planner + Section Writer Agents' + TQ)
lines.append('import json, logging')
lines.append('from typing import Optional')
lines.append('from app.agents.base import BaseAgent')
lines.append('from app.contracts.document_template import DocumentTemplate, SectionSpec, SectionType, TEMPLATE_REGISTRY, get_template')
lines.append('')
lines.append('logger = logging.getLogger(__name__)')
lines.append('')
lines.append('')
lines.append('class DocumentPlannerAgent(BaseAgent):')
lines.append('    name = "document_planner"')
lines.append('    display_name = "\U0001f4cb \u6587\u6863\u89c4\u5212Agent"')
lines.append('    description = "\u6839\u636e\u7814\u7a76\u95ee\u9898\u52a8\u6001\u89c4\u5212\u6587\u6863\u7ed3\u6784"')
lines.append('    requires_review = False')
lines.append('    max_retries = 2')
lines.append('    timeout_seconds = 120')
lines.append('')
lines.append('    system_prompt = ' + TQ + 'You are a senior academic document architect. Analyze the research question and prior results, then plan document structure based on the given template. Output strict JSON only.')
lines.append('')
lines.append('JSON Schema:')
lines.append('{{')
lines.append('  "template_id": "template ID used",')
lines.append('  "estimated_total_words": 8000,')
lines.append('  "section_plans": [')
lines.append('    {{')
lines.append('      "section_id": "section ID",')
lines.append('      "content_outline": ["key points list"],')
lines.append('      "key_evidence": ["key evidence to cite"],')
lines.append('      "multimodal_plan": [')
lines.append('        {{"type": "mermaid|latex|table|chart", "description": "detail", "data_source": "source"}}')
lines.append('      ],')
lines.append('      "estimated_words": 800,')
lines.append('      "dependencies_met": true,')
lines.append('      "writing_priority": 1')
lines.append('    }}')
lines.append('  ],')
lines.append('  "cross_section_notes": "cross-section notes",')
lines.append('  "hypothesis_list": ["H1: ...", "H2: ..."],')
lines.append('  "variable_mapping": {{"independent": [], "dependent": [], "control": []}}')
lines.append('}}' + TQ)
lines.append('')
lines.append('    def build_prompt(self, research_question: str, context: str, **kwargs) -> str:')
lines.append('        template_id = kwargs.get("template_id", "nh_202619_track1")')
lines.append('        template = get_template(template_id)')
lines.append('        sections_desc = NL.join([')
lines.append('            f"- {i+1}. {s.section_id}: {s.title_cn}({s.title_en}) [{s.min_words}-{s.max_words}chars] "')
lines.append('            f"type:{s.section_type.value} multimodal:{chr(44).join(s.multimodal_hints)}"')
lines.append('            for i, s in enumerate(template.sections)])')
lines.append('        rules = NL.join(f"- {r}" for r in template.global_quality_rules)')
lines.append('        return f' + TQ + '## Research Question')
lines.append('{research_question}')
lines.append('')
lines.append('## Prior Results Summary')
lines.append('{context[:6000]}')
lines.append('')
lines.append('## Template: {template.template_id} - {template.template_name}')
lines.append('Word count: {template.total_min_words}-{template.total_max_words}')
lines.append('Citation: {template.citation_style}, Bilingual: {template.requires_bilingual}')
lines.append('')
lines.append('### Sections:')
lines.append('{sections_desc}')
lines.append('')
lines.append('### Global Rules:')
lines.append('{rules}')
lines.append('')
lines.append('## Task')
lines.append('Plan the document. Keep hypothesis IDs (H1,H2...) consistent. Unify variable names. Identify multimodal needs. Mark dependencies and writing priority. Base plans on actual prior results, never fabricate.')
lines.append('')
lines.append('Output JSON.' + TQ)
lines.append('')
lines.append('    def parse_plan(self, raw_output: str) -> dict:')
lines.append('        try:')
lines.append('            text = raw_output.strip()')
lines.append('            if "' + BT3 + 'json" in text:')
lines.append('                text = text.split("' + BT3 + 'json")[1].split("' + BT3 + '")[0].strip()')
lines.append('            elif "' + BT3 + '" in text:')
lines.append('                text = text.split("' + BT3 + '")[1].split("' + BT3 + '")[0].strip()')
lines.append('            return json.loads(text)')
lines.append('        except Exception as e:')
lines.append('            logger.warning(f"[DocumentPlanner] JSON parse failed: {e}")')
lines.append('            return {"section_plans": [], "error": str(e)}')
lines.append('')
lines.append('')
lines.append('class SectionWriterAgent(BaseAgent):')
lines.append('    name = "section_writer"')
lines.append('    display_name = "\u270d\ufe0f \u7ae0\u8282\u5199\u4f5cAgent"')
lines.append('    description = "\u6309\u7ae0\u8282\u89c4\u683c\u751f\u6210\u9ad8\u8d28\u91cf\u5b66\u672f\u5185\u5bb9"')
lines.append('    requires_review = False')
lines.append('    max_retries = 3')
lines.append('    timeout_seconds = 180')
lines.append('')
lines.append('    system_prompt = ' + TQ + 'You are a top academic writing expert. Principles:')
lines.append('1. Every paragraph must have substance, no filler')
lines.append('2. Statistical claims must be specific: coefficient direction, significance level, effect size, CI')
lines.append('3. Distinguish evidence: empirical / theoretical / inference / pending')
lines.append('4. Mark [pending] when info insufficient, never fabricate')
lines.append('5. Multimodal elements must be complete and renderable:')
lines.append('   - Mermaid: full syntax in ' + BT3 + 'mermaid blocks')
lines.append('   - LaTeX formulas: use ' + D + '...' + D + ' (inline) or ' + DD + '...' + DD + ' (display)')
lines.append('   - Tables: standard Markdown table syntax')
lines.append('6. Rigorous logic: every claim backed by evidence')
lines.append('7. Academic but clear style' + TQ)
lines.append('')
lines.append('    def build_prompt(self, research_question: str, context: str, **kwargs) -> str:')
lines.append('        section_spec: Optional[SectionSpec] = kwargs.get("section_spec")')
lines.append('        section_plan: dict = kwargs.get("section_plan", {})')
lines.append('        completed_sections: dict = kwargs.get("completed_sections", {})')
lines.append('        hypothesis_list: list = kwargs.get("hypothesis_list", [])')
lines.append('        if not section_spec:')
lines.append('            raise ValueError("SectionWriterAgent requires section_spec")')
lines.append('        ctx_parts = [f"[{sid}summary]: {c[:500]}" for sid, c in completed_sections.items()]')
lines.append('        prior = NL.join(ctx_parts)[:4000]')
lines.append('        mm_req = ""')
lines.append('        if section_spec.multimodal_hints:')
lines.append('            items = []')
lines.append('            for h in section_spec.multimodal_hints:')
lines.append('                if "mermaid" in h:')
lines.append('                    items.append(f"- Include complete Mermaid diagram (type: {h}) in ' + BT3 + 'mermaid block")')
lines.append('                elif "latex" in h or "formula" in h:')
lines.append('                    items.append(f"- Include LaTeX formulas using ' + D + '...' + D + ' inline or ' + DD + '...' + DD + ' display")')
lines.append('                elif "table" in h:')
lines.append('                    items.append("- Include standard Markdown data table")')
lines.append('                elif "chart" in h:')
lines.append('                    items.append("- Include visualization chart or Mermaid diagram")')
lines.append('            mm_req = NL.join(items)')
lines.append('        hypo = ""')
lines.append('        if hypothesis_list:')
lines.append('            hypo = NL + "Hypothesis IDs (must be consistent):" + NL + NL.join(f"  {x}" for x in hypothesis_list)')
lines.append('        outline = ""')
lines.append('        if section_plan.get("content_outline"):')
lines.append('            outline = NL + "Planned outline:" + NL + NL.join(f"  - {p}" for p in section_plan["content_outline"])')
lines.append('        elems = NL.join(f"- {e}" for e in section_spec.required_elements)')
lines.append('        return f' + TQ + '## Section Spec')
lines.append('ID: {section_spec.section_id}')
lines.append('Title: ## {section_spec.title_cn}({section_spec.title_en})')
lines.append('Words: {section_spec.min_words}-{section_spec.max_words}')
lines.append('Type: {section_spec.section_type.value}')
lines.append('')
lines.append('## Required Elements')
lines.append('{elems}')
lines.append('')
lines.append('## Writing Guide')
lines.append('{section_spec.template_instructions}')
lines.append('')
lines.append('## Multimodal Requirements')
lines.append('{mm_req if mm_req else "No special multimodal requirements; tables encouraged"}')
lines.append('')
lines.append('## Research Question')
lines.append('{research_question}')
lines.append('{hypo}')
lines.append('{outline}')
lines.append('')
lines.append('## Prior Sections Summary')
lines.append('{prior if prior else "(first section)"}')
lines.append('')
lines.append('## Prior Results')
lines.append('{context[:5000]}')
lines.append('')
lines.append('## Output Rules')
lines.append('1. Start with "## {section_spec.title_cn}({section_spec.title_en})"')
lines.append('2. Output section content directly, no meta-commentary')
lines.append('3. Word count: {section_spec.min_words}-{section_spec.max_words}')
lines.append('4. Mark [pending] if info insufficient')
lines.append('5. All statistical claims need evidence')
lines.append('6. Consistent terminology with prior sections' + TQ)

# Need NL defined before join
NL = chr(10)
w('agents/doc_planner.py', NL.join(lines))
print('doc_planner.py done')
