import pathlib, os

BASE = pathlib.Path('backend/app')

def w(rel, content):
    p = BASE / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding='utf-8')
    print(f'  wrote {p} ({len(content)} bytes)')

NL = chr(10)
TQ = chr(34) * 3
BT3 = chr(96) * 3

print('Generating doc_reviewer.py ...')

lines = []
lines.append(TQ + 'Document Reviewer Agent - reviews sections and full documents' + TQ)
lines.append('import json, logging')
lines.append('from typing import Optional')
lines.append('from app.agents.base import BaseAgent')
lines.append('')
lines.append('logger = logging.getLogger(__name__)')
lines.append('')
lines.append('')
lines.append('class SectionReviewerAgent(BaseAgent):')
lines.append('    name = "section_reviewer"')
lines.append('    display_name = "\U0001f50d \u7ae0\u8282\u5ba1\u7a3fAgent"')
lines.append('    description = "\u5ba1\u67e5\u7ae0\u8282\u5185\u5bb9\u8d28\u91cf\u3001\u903b\u8f91\u4e00\u81f4\u6027\u3001\u591a\u6a21\u6001\u5b8c\u6574\u6027"')
lines.append('    requires_review = False')
lines.append('    max_retries = 2')
lines.append('    timeout_seconds = 120')
lines.append('')
lines.append('    system_prompt = ' + TQ + 'You are a rigorous academic peer reviewer. Evaluate the section against these criteria:')
lines.append('1. Content completeness: all required elements present?')
lines.append('2. Evidence quality: statistical claims specific (coefficient, p-value, CI, effect size)?')
lines.append('3. Logic consistency: no contradictions with prior sections?')
lines.append('4. Multimodal correctness: Mermaid/LaTeX/tables syntactically valid and renderable?')
lines.append('5. Word count within specified range?')
lines.append('6. No fabricated data or unsupported claims?')
lines.append('')
lines.append('Output strict JSON:')
lines.append('{')
lines.append('  "approved": true/false,')
lines.append('  "score": 1-10,')
lines.append('  "issues": [{"type": "category", "severity": "high|medium|low", "description": "...", "suggestion": "..."}],')
lines.append('  "summary": "brief review summary"')
lines.append('}' + TQ)
lines.append('')
lines.append('    def build_prompt(self, research_question: str, context: str, **kwargs) -> str:')
lines.append('        section_id = kwargs.get("section_id", "unknown")')
lines.append('        section_content = kwargs.get("section_content", "")')
lines.append('        section_spec = kwargs.get("section_spec")')
lines.append('        spec_desc = ""')
lines.append('        if section_spec:')
lines.append('            spec_desc = f"Section: {section_spec.section_id} | {section_spec.title_cn}({section_spec.title_en})" + NL')
lines.append('            spec_desc += f"Required elements: {section_spec.required_elements}" + NL')
lines.append('            spec_desc += f"Word range: {section_spec.min_words}-{section_spec.max_words}" + NL')
lines.append('            spec_desc += f"Multimodal hints: {section_spec.multimodal_hints}"')
lines.append('        return f' + TQ + '## Review Request')
lines.append('{spec_desc}')
lines.append('')
lines.append('## Research Question')
lines.append('{research_question}')
lines.append('')
lines.append('## Section Content to Review')
lines.append('{section_content}')
lines.append('')
lines.append('## Prior Context (summary)')
lines.append('{context[:3000]}')
lines.append('')
lines.append('Review strictly per criteria. Output JSON.' + TQ)
lines.append('')
lines.append('    def parse_review(self, raw_output: str) -> dict:')
lines.append('        try:')
lines.append('            text = raw_output.strip()')
lines.append('            if "' + BT3 + 'json" in text:')
lines.append('                text = text.split("' + BT3 + 'json")[1].split("' + BT3 + '")[0].strip()')
lines.append('            elif "' + BT3 + '" in text:')
lines.append('                text = text.split("' + BT3 + '")[1].split("' + BT3 + '")[0].strip()')
lines.append('            return json.loads(text)')
lines.append('        except Exception as e:')
lines.append('            logger.warning(f"[SectionReviewer] JSON parse failed: {e}")')
lines.append('            return {"approved": False, "score": 0, "issues": [], "error": str(e)}')
lines.append('')
lines.append('')
lines.append('class DocumentReviewerAgent(BaseAgent):')
lines.append('    name = "document_reviewer"')
lines.append('    display_name = "\U0001f4dd \u5168\u6587\u5ba1\u7a3fAgent"')
lines.append('    description = "\u5ba1\u67e5\u5b8c\u6574\u6587\u6863\u7684\u6574\u4f53\u8d28\u91cf\u3001\u7ed3\u6784\u5b8c\u6574\u6027\u3001\u5b66\u672f\u89c4\u8303"')
lines.append('    requires_review = False')
lines.append('    max_retries = 2')
lines.append('    timeout_seconds = 180')
lines.append('')
lines.append('    system_prompt = ' + TQ + 'You are a senior journal editor reviewing a complete academic document. Evaluate:')
lines.append('1. Overall structure coherence and logical flow')
lines.append('2. Cross-section consistency (terminology, hypothesis IDs, variable names)')
lines.append('3. All multimodal elements renderable and properly referenced')
lines.append('4. Citation format compliance')
lines.append('5. Bilingual title compliance (if required)')
lines.append('6. Total word count within target range')
lines.append('7. No orphaned [pending] markers without justification')
lines.append('')
lines.append('Output strict JSON:')
lines.append('{')
lines.append('  "approved": true/false,')
lines.append('  "overall_score": 1-10,')
lines.append('  "section_scores": {"section_id": score},')
lines.append('  "critical_issues": ["list of must-fix issues"],')
lines.append('  "suggestions": ["optional improvements"],')
lines.append('  "ready_for_submission": true/false')
lines.append('}' + TQ)
lines.append('')
lines.append('    def build_prompt(self, research_question: str, context: str, **kwargs) -> str:')
lines.append('        document = kwargs.get("document", "")')
lines.append('        template_id = kwargs.get("template_id", "")')
lines.append('        plan = kwargs.get("plan", {})')
lines.append('        return f' + TQ + '## Full Document Review')
lines.append('Template: {template_id}')
lines.append('Research Question: {research_question}')
lines.append('')
lines.append('## Complete Document')
lines.append('{document}')
lines.append('')
lines.append('## Generation Plan Summary')
lines.append('{json.dumps(plan, ensure_ascii=False, indent=2)[:2000]}')
lines.append('')
lines.append('Review as senior editor. Output JSON.' + TQ)
lines.append('')
lines.append('    def parse_review(self, raw_output: str) -> dict:')
lines.append('        try:')
lines.append('            text = raw_output.strip()')
lines.append('            if "' + BT3 + 'json" in text:')
lines.append('                text = text.split("' + BT3 + 'json")[1].split("' + BT3 + '")[0].strip()')
lines.append('            elif "' + BT3 + '" in text:')
lines.append('                text = text.split("' + BT3 + '")[1].split("' + BT3 + '")[0].strip()')
lines.append('            return json.loads(text)')
lines.append('        except Exception as e:')
lines.append('            logger.warning(f"[DocumentReviewer] JSON parse failed: {e}")')
lines.append('            return {"approved": False, "overall_score": 0, "error": str(e)}')

w('agents/doc_reviewer.py', NL.join(lines))
print('doc_reviewer.py done')


# === Update agents/__init__.py ===
print('Updating agents/__init__.py ...')
agents_init = BASE / 'agents' / '__init__.py'
existing = agents_init.read_text(encoding='utf-8') if agents_init.exists() else ''
new_imports = [
    'from app.agents.doc_reviewer import SectionReviewerAgent, DocumentReviewerAgent',
]
added = [imp for imp in new_imports if imp not in existing]
if added:
    updated = existing.rstrip() + NL + NL.join(added) + NL
    agents_init.write_text(updated, encoding='utf-8')
    print(f'  updated (+{len(added)} imports)')
else:
    print('  already up to date')

print('Reviewer agents generated!')
